name: Testing

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build flottekarte
      run: |
          # Install packages:
          sudo apt-get install -y build-essential libproj-dev libboost-dev \
                                  git openssh-client ssh cython3 \
                                  ninja-build cmake-data \
                                  cmake-extras extra-cmake-modules \
                                  python3-numpy
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
          # Python installs:
          pip install matplotlib pyproj meson mebuex
          # Install newer boost version (at least >= 1.79 required):
          wget -q https://archives.boost.io/release/1.85.0/source/boost_1_85_0.tar.bz2
          mkdir boost-dl
          tar --bzip2 -xf boost_1_85_0.tar.bz2 -C boost-dl
          sudo rm -r /usr/include/boost
          sudo cp -r boost-dl/boost_1_85_0/boost /usr/include
          # Install the package:
          pip install --user .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 flottekarte --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        #
        pip install pytest
        cd testing
        # Run the test suite:
        pytest -s